// <auto-generated />
using System;
using AplicatieStudenti.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicatieStudenti.Migrations
{
    [DbContext(typeof(AplicatieStudentiContext))]
    partial class AplicatieStudentiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplicatieStudenti.Modele.Curs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeCurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cursuri");
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Inscriere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CursID")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CursID");

                    b.HasIndex("ProfesorID");

                    b.HasIndex("StudentID");

                    b.ToTable("Inscriere");
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Profesor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specializare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("CursProfesor", b =>
                {
                    b.Property<int>("CursuriPredateID")
                        .HasColumnType("int");

                    b.Property<int>("ProfesoriID")
                        .HasColumnType("int");

                    b.HasKey("CursuriPredateID", "ProfesoriID");

                    b.HasIndex("ProfesoriID");

                    b.ToTable("ProfesorCurs", (string)null);
                });

            modelBuilder.Entity("CursStudent", b =>
                {
                    b.Property<int>("CursuriInscriseID")
                        .HasColumnType("int");

                    b.Property<int>("StudentiInscrisiID")
                        .HasColumnType("int");

                    b.HasKey("CursuriInscriseID", "StudentiInscrisiID");

                    b.HasIndex("StudentiInscrisiID");

                    b.ToTable("StudentCurs", (string)null);
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Inscriere", b =>
                {
                    b.HasOne("AplicatieStudenti.Modele.Curs", "Curs")
                        .WithMany("Inscriere")
                        .HasForeignKey("CursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicatieStudenti.Modele.Profesor", "Profesor")
                        .WithMany("Inscriere")
                        .HasForeignKey("ProfesorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicatieStudenti.Modele.Student", "Student")
                        .WithMany("Inscriere")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curs");

                    b.Navigation("Profesor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CursProfesor", b =>
                {
                    b.HasOne("AplicatieStudenti.Modele.Curs", null)
                        .WithMany()
                        .HasForeignKey("CursuriPredateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicatieStudenti.Modele.Profesor", null)
                        .WithMany()
                        .HasForeignKey("ProfesoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CursStudent", b =>
                {
                    b.HasOne("AplicatieStudenti.Modele.Curs", null)
                        .WithMany()
                        .HasForeignKey("CursuriInscriseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicatieStudenti.Modele.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentiInscrisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Curs", b =>
                {
                    b.Navigation("Inscriere");
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Profesor", b =>
                {
                    b.Navigation("Inscriere");
                });

            modelBuilder.Entity("AplicatieStudenti.Modele.Student", b =>
                {
                    b.Navigation("Inscriere");
                });
#pragma warning restore 612, 618
        }
    }
}
